"""
tool_exporter.py
Exports an installed tool from the DB into a redistributable package (.zip).

SECURITY RULES:
  - NEVER embed real API key/secret values in the package.
  - Always replace actual secret values with empty slots (default).
  - source_has_existing_value=True is set as metadata, export_secret_allowed=False by default.
  - export_mode controls what happens with secrets:
      "no_secrets"          – slot definitions only, values never included (safest)
      "empty_slots"         – slot definitions with empty placeholder values (default)
      "encrypted_secrets"   – re-encrypt with export key for trusted migration (explicit opt-in)

Package layout inside the .zip:
  manifest.json
  config_schema.json
  install.py
  uninstall.py
  package_checksum.txt

Usage:
    from tool_exporter import export_tool
    result = export_tool(conn, tool_id="stripe_payments", tenant_id=1,
                         output_dir="/tmp/exports", export_mode="empty_slots")
"""

import hashlib
import json
import os
import re
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from tool_secret_store import mask_secret, encrypt_secret, decrypt_secret
from tool_manifest_validator import validate_manifest_dict, compute_package_checksum

# ── Constants ─────────────────────────────────────────────────────────────────
VALID_EXPORT_MODES = {"no_secrets", "empty_slots", "encrypted_secrets"}

EXPORT_KEY_REF = os.environ.get("TOOL_EXPORT_KEY_REF", "export_v1")

# Templates for generated install/uninstall scripts
_INSTALL_PY_TEMPLATE = '''\
"""
install.py  –  {tool_id} v{version}
Auto-generated by tool_exporter. Do not edit manually.
Run via: POST /tools/install  (multipart/form-data, file=<package.zip>)
"""

TOOL_ID   = "{tool_id}"
TOOL_NAME = "{tool_name}"
VERSION   = "{version}"

# Required secret slots that MUST be filled before the tool can be enabled.
# Values are NEVER stored here — they are collected interactively during install.
REQUIRED_SECRET_SLOTS = {required_secret_slots}

# Required config slots with defaults (non-secret).
REQUIRED_CONFIG_SLOTS = {required_config_slots}


def install(conn, tenant_id: int, slot_values: dict):
    """
    Called by tool_installer after slot values are collected.
    conn       – psycopg2 connection (already in transaction)
    tenant_id  – target tenant
    slot_values – {{slot_name: plain_value}} for ALL required slots
    """
    from tool_secret_store import save_secret, save_config
    for slot in REQUIRED_SECRET_SLOTS:
        name = slot["slot_name"]
        if name in slot_values:
            save_secret(conn, tenant_id, TOOL_ID, name, slot_values[name])
    for slot in REQUIRED_CONFIG_SLOTS:
        name = slot["slot_name"]
        if name in slot_values:
            save_config(conn, tenant_id, TOOL_ID, name, value_text=slot_values[name])


def verify(conn, tenant_id: int) -> bool:
    """Return True if all required secret slots are present in DB."""
    from tool_secret_store import load_secret
    for slot in REQUIRED_SECRET_SLOTS:
        if slot.get("required", True):
            val = load_secret(conn, tenant_id, TOOL_ID, slot["slot_name"])
            if not val:
                return False
    return True
'''

_UNINSTALL_PY_TEMPLATE = '''\
"""
uninstall.py  –  {tool_id} v{version}
Auto-generated by tool_exporter. Do not edit manually.
"""

TOOL_ID = "{tool_id}"


def uninstall(conn, tenant_id: int, purge_secrets: bool = False):
    """
    Deactivate tool config.  Set purge_secrets=True to also remove secrets.
    conn       – psycopg2 connection (already in transaction)
    tenant_id  – target tenant
    """
    with conn.cursor() as cur:
        cur.execute("""
            UPDATE crm.tenant_tool_config
               SET is_active = FALSE, updated_at = NOW()
             WHERE tenant_id = %s AND tool_id = %s
        """, (tenant_id, TOOL_ID))
        if purge_secrets:
            cur.execute("""
                UPDATE crm.tenant_tool_secret
                   SET is_active = FALSE, updated_at = NOW()
                 WHERE tenant_id = %s AND tool_id = %s
            """, (tenant_id, TOOL_ID))
        cur.execute("""
            UPDATE crm.tool_registry
               SET install_status = \'uninstalled\', updated_at = NOW()
             WHERE tenant_id = %s AND tool_id = %s
        """, (tenant_id, TOOL_ID))
'''


# ── DB loaders ────────────────────────────────────────────────────────────────

def _load_tool_registry(conn, tool_id: str, tenant_id: int) -> dict:
    """Load the tool_registry row for this tenant."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT tr.tool_id, tr.tool_name, tr.description, tr.version,
                   tr.author, tr.risk_level, tr.entry_point,
                   tr.install_status, tr.license_type,
                   tr.supported_platforms, tr.install_script, tr.uninstall_script,
                   tr.metadata_json
              FROM crm.tool_registry tr
             WHERE tr.tool_id = %s AND tr.tenant_id = %s
        """, (tool_id, tenant_id))
        row = cur.fetchone()
    if not row:
        raise ValueError(f"Tool '{tool_id}' not found in tool_registry for tenant {tenant_id}")
    return dict(row)


def _load_tool_permissions(conn, tool_id: str) -> list[dict]:
    """Load required_permissions list from tool_permissions table (if exists)."""
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT permission_code, description, scope
                  FROM crm.tool_permissions
                 WHERE tool_id = %s
                 ORDER BY sort_order NULLS LAST, permission_code
            """, (tool_id,))
            return [dict(r) for r in cur.fetchall()]
    except Exception:
        return []


def _load_voice_commands(conn, tool_id: str) -> list[dict]:
    """Load voice_commands from tool_voice_commands table (if exists)."""
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT command_phrase, command_type, language_code, description
                  FROM crm.tool_voice_commands
                 WHERE tool_id = %s
                 ORDER BY language_code, command_phrase
            """, (tool_id,))
            return [dict(r) for r in cur.fetchall()]
    except Exception:
        return []


def _load_pricing(conn, tool_id: str) -> dict | None:
    """Load pricing/billing info from tool_pricing table (if exists)."""
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT pricing_model, price_monthly, price_yearly, currency,
                       trial_days, notes
                  FROM crm.tool_pricing
                 WHERE tool_id = %s
                 LIMIT 1
            """, (tool_id,))
            row = cur.fetchone()
            return dict(row) if row else None
    except Exception:
        return None


def _load_config_slots(conn, tool_id: str) -> list[dict]:
    """Load config slot definitions from tool_config_slots."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT slot_name, display_name, description, required, secret,
                   replaceable, stored_in, validation_type, default_value,
                   enum_options, scope, sort_order
              FROM crm.tool_config_slots
             WHERE tool_id = %s
             ORDER BY COALESCE(sort_order, 9999), slot_name
        """, (tool_id,))
        return [dict(r) for r in cur.fetchall()]


def _load_tenant_config_values(conn, tool_id: str, tenant_id: int) -> dict[str, str]:
    """Load plain config values from tenant_tool_config (non-secret)."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT slot_name, value_text, value_json
              FROM crm.tenant_tool_config
             WHERE tenant_id = %s AND tool_id = %s AND is_active = TRUE
        """, (tenant_id, tool_id))
        result = {}
        for row in cur.fetchall():
            if row["value_text"] is not None:
                result[row["slot_name"]] = row["value_text"]
            elif row["value_json"] is not None:
                result[row["slot_name"]] = json.dumps(row["value_json"])
        return result


def _check_tenant_secret_exists(conn, tool_id: str, tenant_id: int,
                                 slot_name: str) -> bool:
    """Return True if an active secret exists for this slot (do NOT read the value)."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT 1 FROM crm.tenant_tool_secret
             WHERE tenant_id = %s AND tool_id = %s AND slot_name = %s
               AND is_active = TRUE
             LIMIT 1
        """, (tenant_id, tool_id, slot_name))
        return cur.fetchone() is not None


def _load_and_decrypt_secret(conn, tool_id: str, tenant_id: int,
                               slot_name: str) -> str | None:
    """Decrypt a secret. ONLY called in encrypted_secrets export mode."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT encrypted_value, encryption_key_ref
              FROM crm.tenant_tool_secret
             WHERE tenant_id = %s AND tool_id = %s AND slot_name = %s
               AND is_active = TRUE
             LIMIT 1
        """, (tenant_id, tool_id, slot_name))
        row = cur.fetchone()
    if not row:
        return None
    try:
        return decrypt_secret(row["encrypted_value"], row["encryption_key_ref"])
    except Exception:
        return None


def _load_db_requirements(conn, tool_id: str) -> list[dict]:
    """Load DB schema requirements (if tool_db_requirements table exists)."""
    try:
        with conn.cursor() as cur:
            cur.execute("""
                SELECT requirement_type, description, migration_file
                  FROM crm.tool_db_requirements
                 WHERE tool_id = %s
                 ORDER BY sort_order NULLS LAST
            """, (tool_id,))
            return [dict(r) for r in cur.fetchall()]
    except Exception:
        return []


# ── Manifest builder ──────────────────────────────────────────────────────────

def _build_manifest(
    registry: dict,
    permissions: list[dict],
    voice_commands: list[dict],
    pricing: dict | None,
    config_slots: list[dict],
    db_requirements: list[dict],
) -> dict:
    """
    Construct manifest.json from DB-loaded data.
    API values are NEVER included — only slot definitions.
    """
    secret_slots = [s for s in config_slots if s.get("secret")]
    config_only_slots = [s for s in config_slots if not s.get("secret")]

    def _slot_def(slot: dict, has_value: bool = False) -> dict:
        return {
            "slot_name":                 slot["slot_name"],
            "display_name":              slot.get("display_name") or slot["slot_name"],
            "description":               slot.get("description") or "",
            "required":                  bool(slot.get("required", True)),
            "secret":                    bool(slot.get("secret", False)),
            "replaceable":               bool(slot.get("replaceable", True)),
            "stored_in":                 slot.get("stored_in") or (
                                             "tenant_tool_secret" if slot.get("secret")
                                             else "tenant_tool_config"
                                         ),
            "validation_type":           slot.get("validation_type") or "text",
            "source_has_existing_value": has_value,   # metadata hint — no actual value
            "export_secret_allowed":     False,        # always False in slot definitions
        }

    manifest = {
        "tool_id":            registry["tool_id"],
        "tool_name":          registry.get("tool_name") or registry["tool_id"],
        "description":        registry.get("description") or "",
        "version":            registry.get("version") or "1.0.0",
        "author":             registry.get("author") or "unknown",
        "risk_level":         registry.get("risk_level") or "medium",
        "entry_point":        registry.get("entry_point") or "install.py",
        "install_script":     registry.get("install_script") or "install.py",
        "uninstall_script":   registry.get("uninstall_script") or "uninstall.py",
        "license_type":       registry.get("license_type") or "proprietary",
        "supported_platforms": registry.get("supported_platforms") or ["all"],
        "required_permissions": [
            {"permission_code": p["permission_code"],
             "description": p.get("description") or "",
             "scope": p.get("scope") or "tenant"}
            for p in permissions
        ],
        "required_config_slots": [_slot_def(s) for s in config_only_slots],
        "required_secret_slots": [_slot_def(s) for s in secret_slots],
        "voice_commands": voice_commands or [],
        "db_requirements": db_requirements or [],
    }

    if pricing:
        manifest["pricing"] = pricing

    if registry.get("metadata_json"):
        manifest["metadata"] = (
            registry["metadata_json"]
            if isinstance(registry["metadata_json"], dict)
            else json.loads(registry["metadata_json"])
        )

    return manifest


# ── Config schema builder ─────────────────────────────────────────────────────

def _build_config_schema(config_slots: list[dict]) -> dict:
    """Build config_schema.json from slot definitions."""
    slots_out = []
    for slot in config_slots:
        entry = {
            "slot_name":       slot["slot_name"],
            "display_name":    slot.get("display_name") or slot["slot_name"],
            "description":     slot.get("description") or "",
            "required":        bool(slot.get("required", True)),
            "secret":          bool(slot.get("secret", False)),
            "replaceable":     bool(slot.get("replaceable", True)),
            "validation_type": slot.get("validation_type") or "text",
            "stored_in":       slot.get("stored_in") or (
                                   "tenant_tool_secret" if slot.get("secret")
                                   else "tenant_tool_config"
                               ),
            "scope":           slot.get("scope") or "tenant",
        }
        if slot.get("default_value") is not None:
            entry["default_value"] = slot["default_value"]
        if slot.get("enum_options"):
            entry["enum_options"] = (
                slot["enum_options"] if isinstance(slot["enum_options"], list)
                else json.loads(slot["enum_options"])
            )
        slots_out.append(entry)
    return {"slots": slots_out}


# ── Install/uninstall script generators ──────────────────────────────────────

def _build_install_py(
    tool_id: str,
    tool_name: str,
    version: str,
    config_slots: list[dict],
) -> str:
    secret_slots = [s for s in config_slots if s.get("secret")]
    config_only = [s for s in config_slots if not s.get("secret")]

    def _slot_summary(slots):
        out = []
        for s in slots:
            out.append({
                "slot_name":       s["slot_name"],
                "display_name":    s.get("display_name") or s["slot_name"],
                "required":        bool(s.get("required", True)),
                "validation_type": s.get("validation_type") or "text",
            })
        return json.dumps(out, indent=4)

    return _INSTALL_PY_TEMPLATE.format(
        tool_id=tool_id,
        tool_name=tool_name,
        version=version,
        required_secret_slots=_slot_summary(secret_slots),
        required_config_slots=_slot_summary(config_only),
    )


def _build_uninstall_py(tool_id: str, version: str) -> str:
    return _UNINSTALL_PY_TEMPLATE.format(tool_id=tool_id, version=version)


# ── Zip assembler ─────────────────────────────────────────────────────────────

def _assemble_zip(
    output_path: str,
    manifest: dict,
    config_schema: dict,
    install_py: str,
    uninstall_py: str,
    extra_files: dict[str, str] | None = None,
) -> str:
    """
    Write package files to a temp directory, compute checksum, then zip.
    Returns the path to the created .zip file.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        pkg_dir = Path(tmpdir)

        # Write main files
        (pkg_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        (pkg_dir / "config_schema.json").write_text(
            json.dumps(config_schema, indent=2, ensure_ascii=False), encoding="utf-8"
        )
        (pkg_dir / "install.py").write_text(install_py, encoding="utf-8")
        (pkg_dir / "uninstall.py").write_text(uninstall_py, encoding="utf-8")

        if extra_files:
            for name, content in extra_files.items():
                (pkg_dir / name).write_text(content, encoding="utf-8")

        # Compute checksum of package contents (before checksum file itself)
        checksum = compute_package_checksum(pkg_dir)
        (pkg_dir / "package_checksum.txt").write_text(checksum, encoding="utf-8")

        # Zip everything
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            for file_path in sorted(pkg_dir.rglob("*")):
                if file_path.is_file():
                    zf.write(file_path, arcname=file_path.name)

    return output_path


# ── Audit log ─────────────────────────────────────────────────────────────────

def _write_export_log(
    conn, tenant_id: int, tool_id: str,
    export_mode: str, secrets_exported: bool,
    package_path: str, checksum: str,
    exported_by: int | None,
):
    """Write an entry to crm.tool_export_logs."""
    try:
        import json as _json
        details = {"package_path": package_path, "checksum": checksum}
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO crm.tool_export_logs
                    (tenant_id, tool_id, export_mode, export_status,
                     export_details_json, secrets_exported, exported_by, exported_at)
                VALUES (%s, %s, %s, 'success', %s::jsonb, %s, %s, NOW())
            """, (tenant_id, tool_id, export_mode,
                  _json.dumps(details), secrets_exported, exported_by))
    except Exception:
        pass  # best-effort — export still succeeds


# ── Secret slot value handling for export modes ───────────────────────────────

def _apply_export_mode_to_manifest(
    manifest: dict,
    conn,
    tool_id: str,
    tenant_id: int,
    config_slots: list[dict],
    export_mode: str,
) -> tuple[dict, bool]:
    """
    Annotate secret slots in manifest depending on export_mode.
    Returns (updated_manifest, secrets_were_exported).

    Modes:
      no_secrets        – mark source_has_existing_value only, no values
      empty_slots       – same as no_secrets (values remain empty)
      encrypted_secrets – encrypt current secret values with EXPORT_KEY_REF,
                          embed as export_encrypted_value in slot definition
                          (installer must re-encrypt with local key on install)
    """
    if export_mode == "no_secrets":
        # Already safe — secret slot definitions have no values
        return manifest, False

    if export_mode == "empty_slots":
        # Mark source_has_existing_value from DB
        for slot in manifest.get("required_secret_slots", []):
            sname = slot["slot_name"]
            slot["source_has_existing_value"] = _check_tenant_secret_exists(
                conn, tool_id, tenant_id, sname
            )
        return manifest, False

    if export_mode == "encrypted_secrets":
        secrets_exported = False
        for slot in manifest.get("required_secret_slots", []):
            sname = slot["slot_name"]
            plain = _load_and_decrypt_secret(conn, tool_id, tenant_id, sname)
            if plain:
                # Re-encrypt with the export key (NOT the storage key)
                slot["export_encrypted_value"] = encrypt_secret(plain, EXPORT_KEY_REF)
                slot["export_key_ref"] = EXPORT_KEY_REF
                slot["source_has_existing_value"] = True
                secrets_exported = True
        return manifest, secrets_exported

    raise ValueError(f"Unknown export_mode: '{export_mode}'")


# ── Main entry point ──────────────────────────────────────────────────────────

def export_tool(
    conn,
    tool_id: str,
    tenant_id: int,
    output_dir: str,
    export_mode: str = "empty_slots",
    exported_by: int | None = None,
) -> dict:
    """
    Export an installed tool to a .zip package.

    conn         – psycopg2 connection
    tool_id      – tool identifier (snake_case)
    tenant_id    – source tenant to read config from
    output_dir   – directory where the .zip will be saved
    export_mode  – "no_secrets" | "empty_slots" | "encrypted_secrets"
    exported_by  – user_id for audit log

    Returns:
        {
          "tool_id":       str,
          "version":       str,
          "package_path":  str,   # absolute path to .zip
          "checksum":      str,   # sha256 of package contents
          "export_mode":   str,
          "secrets_exported": bool,
          "slot_count":    int,
          "secret_slot_count": int,
          "warnings":      list[str],
        }
    """
    if export_mode not in VALID_EXPORT_MODES:
        raise ValueError(
            f"Invalid export_mode '{export_mode}'. "
            f"Must be one of {VALID_EXPORT_MODES}"
        )

    warnings: list[str] = []

    # 1. Load all data from DB
    registry    = _load_tool_registry(conn, tool_id, tenant_id)
    permissions = _load_tool_permissions(conn, tool_id)
    voice_cmds  = _load_voice_commands(conn, tool_id)
    pricing     = _load_pricing(conn, tool_id)
    config_slots = _load_config_slots(conn, tool_id)
    db_reqs     = _load_db_requirements(conn, tool_id)

    if not config_slots:
        warnings.append("No config_slots defined in tool_config_slots — package will have no slot definitions.")

    # 2. Build manifest + config_schema
    manifest      = _build_manifest(registry, permissions, voice_cmds, pricing, config_slots, db_reqs)
    config_schema = _build_config_schema(config_slots)

    # 3. Apply export mode (annotate/include secret values per mode)
    manifest, secrets_exported = _apply_export_mode_to_manifest(
        manifest, conn, tool_id, tenant_id, config_slots, export_mode
    )

    # 4. Validate manifest (fail fast before creating the zip)
    validation = validate_manifest_dict(manifest, config_schema)
    if not validation["valid"]:
        raise ValueError(
            f"Generated manifest failed validation:\n" +
            "\n".join(f"  - {e}" for e in validation["errors"])
        )
    if validation["warnings"]:
        warnings.extend([f"Manifest warning: {w}" for w in validation["warnings"]])

    # 5. Generate install/uninstall scripts
    install_py   = _build_install_py(
        tool_id, registry.get("tool_name") or tool_id,
        registry.get("version") or "1.0.0", config_slots
    )
    uninstall_py = _build_uninstall_py(tool_id, registry.get("version") or "1.0.0")

    # 6. Assemble zip
    version = manifest["version"].replace(".", "_")
    filename = f"{tool_id}_v{version}_{export_mode}.zip"
    output_path = os.path.join(output_dir, filename)
    _assemble_zip(output_path, manifest, config_schema, install_py, uninstall_py)

    # 7. Read checksum back from the zip (from package_checksum.txt inside)
    checksum = ""
    with zipfile.ZipFile(output_path, "r") as zf:
        if "package_checksum.txt" in zf.namelist():
            checksum = zf.read("package_checksum.txt").decode().strip()

    # 8. Write export audit log
    _write_export_log(
        conn, tenant_id, tool_id, export_mode, secrets_exported,
        output_path, checksum, exported_by
    )

    secret_slots = [s for s in config_slots if s.get("secret")]

    return {
        "tool_id":           tool_id,
        "version":           manifest["version"],
        "package_path":      output_path,
        "checksum":          checksum,
        "export_mode":       export_mode,
        "secrets_exported":  secrets_exported,
        "slot_count":        len(config_slots),
        "secret_slot_count": len(secret_slots),
        "warnings":          warnings,
    }


# ── CLI wrapper ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse
    import psycopg2
    import psycopg2.extras

    parser = argparse.ArgumentParser(description="Export a tool package")
    parser.add_argument("tool_id",                     help="Tool ID to export")
    parser.add_argument("--tenant-id",  type=int, default=1)
    parser.add_argument("--output-dir", default="./exports")
    parser.add_argument("--export-mode", default="empty_slots",
                        choices=list(VALID_EXPORT_MODES))
    parser.add_argument("--db-url", default=os.environ.get("DATABASE_URL"))
    args = parser.parse_args()

    if not args.db_url:
        print("Error: --db-url or DATABASE_URL env required", file=sys.stderr)
        sys.exit(1)

    conn = psycopg2.connect(args.db_url, cursor_factory=psycopg2.extras.RealDictCursor)
    conn.autocommit = False
    try:
        result = export_tool(
            conn,
            tool_id=args.tool_id,
            tenant_id=args.tenant_id,
            output_dir=args.output_dir,
            export_mode=args.export_mode,
        )
        conn.commit()
        print(json.dumps(result, indent=2))
    except Exception as e:
        conn.rollback()
        print(f"Export failed: {e}", file=sys.stderr)
        sys.exit(1)
    finally:
        conn.close()
